### ISSUE TITLE
Offer statistics dashboard

### ISSUE THREAD

**Issue by alpakido** [Holo-Host/holo-auth#7]
cc @jmday 

Given data that is available in various APIs, it wouldn't be challenging to create a page that would show generalized stats like how many emails we've sent out (w/o counting in @holo.host registrations). If desirable, that could also be split by countries, or any other way you see fit. 

This might not be urgent, but probably makes sense to discuss, especially considering that from what I gather I broke your statistics generation tools by switching to Postmark. Sorry about that.

**Comment by jmday** [comment]
Thanks @yegortimoshenko ... Yes, indeed. I sense I'll be digging into that API very soon to update our registration metrics & analytics :)

**Comment by yegortimoshenko** [comment]
Could you tell me which stats you want to extract from this data? It's likely we can easily provide them as part of Holo Auth.

**Comment by jmday** [comment]
@yegortimoshenko For now, a list of the registration/failure/etc. emails sent/delivered/opened (with datetime and target email address) should be sufficient.

Eventually, it will make sense to move towards a consolidated view of all related Holo Hosting Network searchable by email, HHID, ZT address, etc... (I've been using a right join with the HoloPort Shipment data so that we have access to all relevant closed alpha customers and just the email data) This aggregation is definitely out of scope for version 1.

**Comment by peeech** [comment]
closing as outdated
