### ISSUE TITLE
Implement missing activation limit

### ISSUE THREAD

**Issue by alpakido** [Holo-Host/holo-auth#8]
cc @alastairong 

Limiting how many times email can be used to activate HoloPort is currently not implemented, as discussed previously. Filing this issue to reflect that fact.

**Comment by yegortimoshenko** [comment]
It could also be that this is not needed anymore. If the need for this changes, let me know.

**Comment by alastairong** [comment]
@yegortimoshenko Thanks for filing this for tracking. CS is also increasingly agreeing that we shouldn’t have this limit implemented but let’s keep it here for now.
 
Functionally, are there any concerns with registering multiple HPs to the same email + password combo? I assume not since the seed entropy still contains some randomness?

**Comment by yegortimoshenko** [comment]
> Functionally, are there any concerns with registering multiple HPs to the same email + password combo? I assume not since the seed entropy still contains some randomness?

No, no problem with that at all, as long as `hpos-config.json` is generated separately for each HoloPort.

**Comment by peeech** [comment]
closing as outdated
